services:
  sample-changer:
    image: flex-server:latest
    container_name: flex-server
    ports:
      - "9001:9001"
    restart: unless-stopped

  minidiff:
    image: arinax:MD
    container_name: arinax-md
    ports:
      - "9002:9001"
    environment:
      - MD_GUI=false
      - MD_BACKGROUND=true
    restart: unless-stopped

#   icat-plus:
#     container_name: icat-plus
#     image: gitlab-registry.esrf.fr/icat/ci-testing-platform/docker-icat-plus:latest
#     restart: unless-stopped
#     ports:
#       - "${ICAT_PLUS_PORT:-8003}:8000"
#     depends_on:
#       - loussertdb
#     extra_hosts:
#       - "host-gateway:host-gateway"
#     environment:
#       WAIT_HOSTS: "loussertdb:27017,host-gateway:${ICAT_SERVER_PORT:-8083}"
#       WAIT_TIMEOUT: 60
#       WAIT_SLEEP_INTERVAL: 5
#       ICAT_SERVER_URL: "${ICAT_SERVER_URL}"
#       ICAT_SERVER_PORT: "${ICAT_SERVER_PORT:-8083}"
#       MESSAGE_ENABLED: 0
#       TRACKING_ENABLED: 0
#       LOGGING_LEVEL: INFO

#   loussertdb:
#     container_name: loussertdb
#     image: harbor.esrf.fr/dau/mongo:24.04
#     restart: unless-stopped
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
#       MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
#       MONGO_INITDB_DATABASE: icatplus
#     volumes:
#       - loussertdb-data:/data/db

# volumes:
#   loussertdb-data:
