---

# yamllint disable rule:line-length

name: Publish on tag

on:       # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUBLISH_ON_TAG_CI_TOKEN }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Publish package to PyPI
        id: publish-pacakge
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry config repositories.gitlab ${{ vars.ESRF_GITLAB_PYPI_URI }}
          poetry config http-basic.gitlab gitlab-ci-token ${{ secrets.ESRF_GITLAB_PYPI_TOKEN }}
          poetry version ${{ github.ref_name }}
          poetry build
          poetry publish --repository gitlab
